---
- name: Set hostname to kwcnc
  hostname:
    name: kwcnc

- name: Update /etc/hosts with new hostname
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 kwcnc.local kwcnc'
    state: present

- name: Ensure localhost entry exists in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 localhost'
    state: present
